### ISSUE TITLE
Disable notification when DND enabled/disabled

### ISSUE THREAD

**Issue by mmahmad** [lucaorio/alfred-do-not-disturb#1]
Hi, 

Would it be possible to provide an option to disable notification whenever DND is enabled/disabled?

Thanks

**Comment by lucaorio** [comment]
Sorry @mmahmad , I've never received an email notification for your comment!

I just pushed an update that removes the notifications. I also had to update how the overall workflow works because of my recent switch to macOS Monterey. :|
